# Generated by Django 5.1.1 on 2024-10-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohan', '0002_my_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_cars',
            name='Image',
            field=models.ImageField(default='rohandjango/rohan/static/img.jpg', upload_to='rohan/'),
        ),
    ]
